#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-urlchecker
Version  : 1.0.1
Release  : 4
URL      : https://cran.r-project.org/src/contrib/urlchecker_1.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/urlchecker_1.0.1.tar.gz
Summary  : Run CRAN URL Checks from Older R Versions
Group    : Development/Tools
License  : GPL-3.0
Requires: R-cli
Requires: R-curl
Requires: R-xml2
BuildRequires : R-cli
BuildRequires : R-curl
BuildRequires : R-xml2
BuildRequires : buildreq-R

%description
package for earlier versions of R. Also uses concurrent requests so
    can be much faster than the serial versions.

%prep
%setup -q -c -n urlchecker
cd %{_builddir}/urlchecker

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1658418500

%install
export SOURCE_DATE_EPOCH=1658418500
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library urlchecker
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library urlchecker
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library urlchecker
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc urlchecker || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/urlchecker/DESCRIPTION
/usr/lib64/R/library/urlchecker/INDEX
/usr/lib64/R/library/urlchecker/Meta/Rd.rds
/usr/lib64/R/library/urlchecker/Meta/features.rds
/usr/lib64/R/library/urlchecker/Meta/hsearch.rds
/usr/lib64/R/library/urlchecker/Meta/links.rds
/usr/lib64/R/library/urlchecker/Meta/nsInfo.rds
/usr/lib64/R/library/urlchecker/Meta/package.rds
/usr/lib64/R/library/urlchecker/NAMESPACE
/usr/lib64/R/library/urlchecker/NEWS.md
/usr/lib64/R/library/urlchecker/R/urlchecker
/usr/lib64/R/library/urlchecker/R/urlchecker.rdb
/usr/lib64/R/library/urlchecker/R/urlchecker.rdx
/usr/lib64/R/library/urlchecker/help/AnIndex
/usr/lib64/R/library/urlchecker/help/aliases.rds
/usr/lib64/R/library/urlchecker/help/paths.rds
/usr/lib64/R/library/urlchecker/help/urlchecker.rdb
/usr/lib64/R/library/urlchecker/help/urlchecker.rdx
/usr/lib64/R/library/urlchecker/html/00Index.html
/usr/lib64/R/library/urlchecker/html/R.css
/usr/lib64/R/library/urlchecker/tools/README.md
/usr/lib64/R/library/urlchecker/tools/urltools.R
/usr/lib64/R/library/urlchecker/tools/utils.R
